version: 2
updates:
  - package-ecosystem: "pip"
    # Files stored in `app` directory
    directory: "/src"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
